export const GET_HEROES_REQUEST = 'GET_HEROES_REQUEST';
export const GET_HEROES = 'GET_HEROES';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE = 'GET_PROFILE';
export const PATCH_POWER_REQUEST = 'PATCH_POWER_REQUEST';
export const PATCH_POWER_COMPLETE = 'PATCH_POWER_COMPLETE';
export const INC_POWER = 'INC_POWER';
export const DEC_POWER = 'DEC_POWER';
